smsTest/config/routes.rb
Rails.application.routes.draw do
  get 'send_sms/index'

  resources :messages

  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

smsTest/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

smsTest/app/models/message.rb
class Message < ApplicationRecord
	validates :sms_number, 
					presence: true,
                    :length => { 	minimum: 10, 
                    			maximum:10 },
                    :format => {:with => /^[0-9]{10}$/i, 
                    			:multiline => true,
                    			:message => "Phone number must be 10 digits, no dashes or non-numerical characters."}
end

smsTest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

smsTest/app/controllers/messages_controller.rb
class MessagesController < ApplicationController


	def index
		@messages = Message.all
	end

	def show
	    @message = Message.find(params[:id])
	end

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params)

		if @message.save
			redirect_to @message
		else
			render 'new'
		end
	end

	private 
		def message_params
			params.require(:message).permit(:sms_number, :sms_text)
		end
end

smsTest/app/controllers/send_sms_controller.rb
class SendSmsController < ApplicationController
  def index
  end
end

smsTest/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

smsTest/app/helpers/application_helper.rb
module ApplicationHelper
end

smsTest/app/helpers/messages_helper.rb
module MessagesHelper
end

smsTest/app/helpers/send_sms_helper.rb
module SendSmsHelper
end

smsTest/app/helpers/welcome_helper.rb
module WelcomeHelper
end

smsTest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmsTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

smsTest/app/views/messages/index.html.erb
<h1>Menu</h1>


<%= link_to 'Home', controller: 'messages' %></p>
<%= link_to 'New message', new_message_path %>

<h1>Sent Messages</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @messages.each do |message| %>
    <tr>
      <td><%= message.sms_number %></td>
      <td><%= message.sms_text %></td>
      <td><%= link_to 'Show', message_path(message) %></td>
    </tr>
  <% end %>
</table> 

smsTest/app/views/messages/new.html.erb
<%= form_for :message, url: messages_path do |f| %>

	<% if @message.errors.any? %>
	    <div id="error_explanation">
	      <h2>
	        Fix the following <%= pluralize(@message.errors.count, "error") %> before sending:
	      </h2>
	      <ul>
	        <% @message.errors.full_messages.each do |msg| %>
	          <li><%= msg %></li>
	        <% end %>
	      </ul>
	    </div>
	<% end %>


  <p>
    <%= f.label :sms_number %><br>
    <%= f.text_field :sms_number %>
  </p>
 
  <p>
    <%= f.label :sms_text %><br>
    <%= f.text_area :sms_text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', messages_path %>

smsTest/app/views/messages/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @message.sms_number %>
</p>
 
<p>
  <strong>Message:</strong>
  <%= @message.sms_text %>
</p>

<%= link_to 'Back', messages_path %>

smsTest/app/views/send_sms/index.html.erb
<h1>SendSms#index</h1>
<p>Find me in app/views/send_sms/index.html.erb</p>

smsTest/app/views/welcome/index.html.erb
this is a test...............